//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTag
    {
        public ItemTag()
        {
            this.Manage_OrderMessage = new HashSet<Manage_OrderMessage>();
        }
    
        public int Itemtagid { get; set; }
        public string ItemTags { get; set; }
        public int Sellerid { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Message { get; set; }
    
        public virtual Seller Seller { get; set; }
        public virtual ICollection<Manage_OrderMessage> Manage_OrderMessage { get; set; }
    }
}
