//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageScheduleMessage
    {
        public decimal ManageEmail_id { get; set; }
        public decimal MessageScheduleid { get; set; }
        public System.DateTime Send_At { get; set; }
        public string Status { get; set; }
        public decimal ContactId { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
