//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSchedule
    {
        public decimal MessageScheduleid { get; set; }
        public int Sellerid { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime Send_At { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
