//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTag
    {
        public decimal MessageTagid { get; set; }
        public decimal Tagid { get; set; }
        public decimal MasterMessageid { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual MasterMessage MasterMessage { get; set; }
    }
}
