//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public Seller()
        {
            this.Templates = new HashSet<Template>();
            this.ItemTags = new HashSet<ItemTag>();
            this.MessageSchedules = new HashSet<MessageSchedule>();
            this.EbayMessages = new HashSet<EbayMessage>();
            this.MasterMessages = new HashSet<MasterMessage>();
        }
    
        public int Sellerid { get; set; }
        public string SellarName { get; set; }
        public string DevID { get; set; }
        public string AppID { get; set; }
        public string CertID { get; set; }
        public string UserToken { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ProxyIP { get; set; }
        public string ProxyPort { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProxyPassword { get; set; }
        public string ProxyUsername { get; set; }
        public Nullable<bool> IsCredentialsRequired { get; set; }
        public bool IsProxyRequired { get; set; }
        public string RuName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<ItemTag> ItemTags { get; set; }
        public virtual ICollection<MessageSchedule> MessageSchedules { get; set; }
        public virtual ICollection<EbayMessage> EbayMessages { get; set; }
        public virtual ICollection<MasterMessage> MasterMessages { get; set; }
    }
}
