//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesSource.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Filterations = new HashSet<Filteration>();
            this.MessageTags = new HashSet<MessageTag>();
        }
    
        public decimal Tagid { get; set; }
        public string TagName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<Filteration> Filterations { get; set; }
        public virtual ICollection<MessageTag> MessageTags { get; set; }
    }
}
